AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Architectures:
      - arm64
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        TABLE: !Ref Table

Resources:
  GenerateLink:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/generate_link/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /generate
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  RedirectLink:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/redirect_link/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /t/{id}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${AWS::StackName} API Gateway CloudFront Distribution'
        DefaultCacheBehavior:
          TargetOriginId: 'ApiGatewayOrigin'
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Headers:
              - Origin
        Origins:
          - Id: 'ApiGatewayOrigin'
            DomainName: !Sub '${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: 'https-only'

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'

  CloudFrontDistributionDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName
