AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Architectures:
      - arm64
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        TABLE: !Ref UrlShortenerTable

Resources:
  GenerateLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/generate_link/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /generate
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlShortenerTable

  RedirectLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/redirect_link/
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /t/{id}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlShortenerTable

  UrlShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - PUT
        AllowOrigins:
          - !Sub https://${CloudFrontDistributionDomainName}/*

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${AWS::StackName} API Gateway CloudFront Distribution'
        DefaultCacheBehavior:
          TargetOriginId: 'ApiGatewayOrigin'
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Headers:
              - Origin
        Origins:
          - Id: 'ApiGatewayOrigin'
            DomainName: !Sub '${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: 'https-only'

  UrlShortenerElastiCacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: 'cache.t2.micro'
      Engine: 'redis'
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref UrlShortenerCacheSubnetGroup
      VpcSecurityGroupIds:
        - !Ref UrlShortenerSecurityGroup

  UrlShortenerCacheSubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: 'ElastiCache Subnet Group for URL Shortener'
      SubnetIds:
        - !Ref UrlShortenerSubnet

  # Security Group for ElastiCache
  UrlShortenerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'ElastiCache Security Group for URL Shortener'
      VpcId: !Ref UrlShortenerVPC

  # VPC Configuration
  UrlShortenerVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  # Subnet Configuration
  UrlShortenerSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref UrlShortenerVPC
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: true

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'

  CloudFrontDistributionDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName

  RedisEndpoint:
    Description: 'Redis Cache Endpoint'
    Value: !GetAtt MyRedisCache.RedisEndpoint.Address
